USE master;
GO

IF DB_ID('JobDW') IS NOT NULL
BEGIN
    ALTER DATABASE JobDW SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE JobDW;
END;
GO

CREATE DATABASE JobDW;
GO

PRINT 'Da tao moi database JobDW';
GO