export const queryKeys = {
  health: ["health"],
  analytics: {
    overview: (params) => ["analytics", "overview", params],
    filters: ["analytics", "filters"],
    quarterTrends: (params) => ["analytics", "trends", "quarters", params],
    monthTrends: (params) => ["analytics", "trends", "months", params],
    positions: (params) => ["analytics", "positions", params],
    positionSkills: (position, params) => [
      "analytics",
      "positions",
      position,
      "skills",
      params,
    ],
    skillsTop: (params) => ["analytics", "skills", "top", params],
    languagesTop: (params) => ["analytics", "languages", "top", params],
    skillCoOccurrence: (params) => [
      "analytics",
      "skills",
      "co-occurrence",
      params,
    ],
    salariesByPosition: (params) => [
      "analytics",
      "salaries",
      "by-position",
      params,
    ],
    salariesByExperience: (params) => [
      "analytics",
      "salaries",
      "by-experience",
      params,
    ],
    salariesByCity: (params) => ["analytics", "salaries", "by-city", params],
    salariesBySkill: (params) => [
      "analytics",
      "salaries",
      "by-skill",
      params,
    ],
    locations: (params) => ["analytics", "locations", params],
    marketsCities: (params) => ["analytics", "markets", "cities", params],
    cityPositions: (city, params) => [
      "analytics",
      "markets",
      "cities",
      city,
      "positions",
      params,
    ],
    companiesTop: (params) => ["analytics", "companies", "top", params],
    companiesByField: (params) => [
      "analytics",
      "companies",
      "by-field",
      params,
    ],
    levels: (params) => ["analytics", "levels", params],
    experienceByPosition: (params) => [
      "analytics",
      "experience",
      "by-position",
      params,
    ],
    levelSkills: (level, params) => [
      "analytics",
      "levels",
      level,
      "skills",
      params,
    ],
    jobsSummary: (params) => ["analytics", "jobs", "summary", params],
    jobsBreakdown: (params) => ["analytics", "jobs", "breakdown", params],
  },
}
